apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::495735830268:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-148JV3GZSN240
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::495735830268:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-24T22:18:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2433"
  uid: 6d288230-b14a-4f72-9c88-a75edfc8dd4d
